-- AlterTable
ALTER TABLE "Activity" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "description" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Attendance" ALTER COLUMN "status" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Error" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "MesoCycle" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "period" SET DATA TYPE TEXT,
ALTER COLUMN "stage" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Trainer" ALTER COLUMN "weapon" SET DATA TYPE TEXT,
ALTER COLUMN "pictureURL" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "TrainingExercise" ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "TrainingGroup" ALTER COLUMN "name" SET DATA TYPE TEXT,
ALTER COLUMN "weapon" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "lastNames" SET DATA TYPE TEXT,
ALTER COLUMN "names" SET DATA TYPE TEXT;
