name: CI WebApp Client

on:
  pull_request:
    branches: [ main ]
    paths: ["Code/Web_app/client/**"]

build_client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn install
      working-directory: Code/Web_app/client
    - name: run linter
      run: yarn lint
      working-directory: Code/Web_app/client
    # - name: Run tests
      # run: yarn test
      # working-directory: Code/Web_app/client
    - name: build frontend
      run: yarn build
      working-directory: Code/Web_app/client